name: 'Build'

on:
  - push
  - pull_request

jobs:
    # NOTE: Newer versions of Xcode will complain and refuse to build old XIB files or target old iOS versions
    ios:
       runs-on: macos-latest
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v3
           with:
               submodules: true
         - name: Build iOS Archive
           run: |
               cd platforms/macos/projects/Minecraft
               xcodebuild -scheme "minecraftpe" \
               -archivePath $RUNNER_TEMP/GitHubActions_iOS.xcarchive \
               -sdk iphoneos \
               -configuration "Release (iOS)" \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO \
               -destination generic/platform=iOS \
               GCC_PREPROCESSOR_DEFINITIONS='MISSING_SOUND_DATA $(GCC_PREPROCESSOR_DEFINITIONS)' \
               -quiet \
               clean archive 
         - name: Upload RUNNER_TEMP directory
           uses: actions/upload-artifact@v3
           with:
             name: runner_temp
             path: /Users/runner/work/_temp
             retention-days: 3
